### PR TITLE
Make FutureKit build with Swift Package Manager

### PR DESCRIPTION
**Pull request by klundberg**
`swift build` previously did not build `FutureKit` with the swift package manager properly. This PR moves files around slightly so that `swift build` will work properly.

I had to delete the ObjectiveCExceptionHandler code to make `swift build` work, since it doesn't support mixed-language targets. This class wasn't exposed anywhere in the framework that I could see, so I don't think this is a big deal.

~I wanted to migrate the unit tests to also work when running `swift test`, but those tests also include obj-c code that appears to be important to the definition of each test. It may be possible to restructure things so that they can compile, but I'm not familiar with how that could look yet.~

I was able to get the tests to build by adding a separate swiftpm target for the `BlockBasedTestCase` objc code, which is imported by the unit tests. `swift test` will now build everything and run the requisite tests properly.

### CODE REVIEW

**Comment by klundberg** [comment]
I rebased this onto the xcode9 branch since I need this to work there. If you want me to recreate the PR i'm happy to do so, if this causes issues

**Comment by mishagray** [comment]
Hmm... the test code will probably need to be refactored since it uses an ObjectiveC runtime binding trick to allow it to 'generate' test code cases.   Not sure how to do that in swift only.
Maybe I could look at using [Stencil](https://github.com/kylef/Stencil).

I'll try and pull this down tonight and run it...

**Comment by klundberg** [comment]
That’s possible. It all works as expected on a Mac but I haven’t tried running this on Linux at all. 

--
Kevin Lundberg

**Comment by klundberg** [comment]
I noticed you made a new release for swift 4 support. I made sure these commits were up to date with that work, and `swift test` still compiles and runs the tests properly

**Pull request closed without merging**
