### PR TITLE
Add Travis CI support

### PR DESCRIPTION
**Pull request by JrGoodle**
Addresses #18

### CODE REVIEW

**Comment by JrGoodle** [comment]
@mishagray These commands worked for me locally, but there may be some configuration necessary for PR's from forks to run on Travis.

**Comment by JrGoodle** [comment]
screenshot 2016-01-25 17 58 52

**Comment by mishagray** [comment]
Thanks!  I'll get this merged in soon!

**Comment by JrGoodle** [comment]
It may require some tweaks once it's running on Travis. Let me know once you've enabled builds for pull requests and I can push a new commit to test (if it doesn't automatically try to build a pre-existing PR).

**Pull request closed without merging**
